# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRnShLNhCCEuUHKCKG90D0_orkG8SRIW
"""

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("My First Streamlit App 🎉")
# st.write("Hello! This app is running from Google Colab 🚀")
# name = st.text_input("Enter your name:")
# if name:
#     st.success(f"Welcome, {name} 👋")

! curl ipv4.icanhazip.com

import threading
import time
import subprocess

# Function to launch streamlit
def launch():
    subprocess.Popen(["streamlit", "run", "streamlitapp.py", "--server.port", "8501"])

# Run streamlit in a separate thread
threading.Thread(target=launch).start()

# Wait a few seconds to make sure Streamlit starts
time.sleep(5)

# Start localtunnel
!npx localtunnel --port 8501