# -*- coding: utf-8 -*-
"""streamlitapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dgDLwfdtyxeBD8TYgExtClF-AxAYbXl0
"""

# Install dependencies
!pip install streamlit
!npm install -g localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlitapp.py
# import streamlit as st
# 
# st.title("My First Streamlit App 🚀")
# st.write("Hello Barath 👋")
#

! curl ipv4.icanhazip.com

import threading
import time
import subprocess

# Function to launch streamlit
def launch():
    subprocess.Popen(["streamlit", "run", "streamlitapp.py", "--server.port", "8501"])

# Run streamlit in a separate thread
threading.Thread(target=launch).start()

# Wait a few seconds to make sure Streamlit starts
time.sleep(5)

# Start localtunnel
!npx localtunnel --port 8501